spring:
  application:
    name: microservicios-company
  datasource:
    name: parking
    url: jdbc:mysql://localhost:3306/emk_billing?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=America/Bogota
    username: root
    password: Ashe_Hada_Dragon_2020_Plata
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
    port: 8082

eureka:
  instance:    instance-id: ${spring.application.name}:${random.value}
  client:    service-url:      default-zone: http://localhost:8761/eureka
